name:                haskell-nix-ghc-bug
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Short description of your package
category:            Web

description:         Please see the README on GitHub at <https://github.com/githubuser/ranger#readme>

dependencies:
- base >= 4.7 && < 5
- ghc

library:
  source-dirs: src
